version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: postgres_db
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: hello1
            POSTGRES_DB: discord-clone
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    # pgadmin:
    #   image: dpage/pgadmin4
    #   container_name: my_pgadmin
    #   restart: always
    #   ports:
    #     - "8080:80"
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #     PGADMIN_DEFAULT_PASSWORD: admin123
    #   depends_on:
    #     - postgres
